### PR TITLE
Preprocessing complete, i think?

### PR DESCRIPTION
**Pull request by LigiaVergara**
Preprocessing complete, i think?

### CODE REVIEW

**Review by MRaza98 — COMMENTED** [review]
are there no missing values anymore? Do you want me to check once more before our session tomorrow?

**Comment by MRaza98** [comment]
> are there no missing values anymore? Do you want me to check once more before our session tomorrow?

otherwise merging

**Comment by LigiaVergara** [comment]
Yes, please!

**Comment by MRaza98** [comment]
Looks good to me but wont merge it as I merged this into my own branch (not the main one) and built upon it. You can review my code on that branch.

**Pull request closed without merging**
